---
- name: Deploy HNG Stage 6 Application
  hosts: web_servers
  become: yes
  vars:
    repo_url: "https://github.com/{{ github_username }}/{{ repo_name }}.git"
    app_dir: "/opt/hng-stage6"
    domain_name: "{{ domain }}"
    duckdns_domain: "{{ duckdns_subdomain | default('') }}"
    duckdns_token: "{{ duckdns_token | default('') }}"
    
  roles:
    - dependencies
    - deploy